# Application (app.R)
source("Functions/themes.R") 
source("Functions/helper.R") 
source("Functions/question_config.R") 
source("Functions/summarize_pert.R")  
source("Functions/plotting_functions.R") 
source("Data/demo_data.R") 
source("App/UI.R") 
source("App/server.R") 
shinyApp(ui, server) 