# -*- coding: utf-8 -*-
"""
Created on Thu Nov 30 14:12:54 2023

@author: wb582890
"""

import numpy as np
import pandas as pd
import pickle
from SourceCode.utils import temporary_storage, MRIO_mat_to_df, MRIO_df_to_vec
# from alive_progress import alive_bar
import gc
# from tqdm import tqdm
from concurrent import futures

class ener_balance:
    """
    This class collects the variables and parameters related to energy balances and emissions and calculates energy flows,
    energy and emissions intensities, energy substitution and emissions by actor.

    Parameters
    ----------
    EXOG_VARS : class
        Class for exogenous variables.
    scenario : class
        Class for scenario assumptions.
    
    Methods
    -----------
    init_ener_vars
        Defines the parameters to be extracted from IEA data.
    calc_fuel_implicit_price
        Calculates implicit fuel prices from output and physical values.
    calc_fuel_prod_base
        Calculates base fuel use.
    calc_fuel_prod_change
        Attaches physical units to all GLORIA monetary flows to calculate implicit prices for the flows
        this is used to keep track of fuel consumption and energy substitution.
    calc_energy_efficiency
        Calculates energy efficiency.
    calc_fuel_substitution
        Calculates fuel substitution based on fuel price changes and output changes.
    hh_fuel_substitution
        Calculates fuel substitution for huoseholds based on fuel price changes and output changes.
    calc_monetary_io_change
        Re-calculates energy related IO coefficients.
    calc_emission_intensities
        Calculates emissions intensities.
    calc_emission_intensities_process
        Calculates process emissions intensities.
    tax_incidence_loop
        Calculates the tax incidence given carbon tax rate files generated by earlier functions 
        (these are stored in the Temp folder).    
    calculate_tax_incidence
        Collects tax data.
    build_emission_matrix
        Creates pullutant base matrix.
    delta_emissions
        Calculates changes in pollutants.
    """ 
    def __init__(self, EXOG_VARS, scenario, refining_sectors):
        self.IND_BASE = EXOG_VARS.IND_BASE.reset_index()
        self.HH_BASE = EXOG_VARS.HH_BASE.reset_index()
        self.GOV_BASE = EXOG_VARS.GOV_BASE.reset_index()
        self.FCF_BASE = EXOG_VARS.FCF_BASE.reset_index()
        self.A_id = EXOG_VARS.A_id
        # self.NPISH = EXOG_VARS.NPISH.reset_index(inplace=True)
        
        self.COU_ID = EXOG_VARS.COU_ID
        self.REGION = EXOG_VARS.R
        self.PRODUCTS = EXOG_VARS.P
        self.E = EXOG_VARS.E
        self.ENERGY_LIST = self.E['Lfd_Nr'].to_list()

        self.R_list = EXOG_VARS.R_list
        self.P_list = EXOG_VARS.P_list

        self.MRIO_df_to_vec_DEF = lambda df,name: MRIO_df_to_vec(df, 'REG_imp','PROD_COMM',name, EXOG_VARS.R_list, EXOG_VARS.P_list)

        self.DIMS = len(self.REGION) * len(self.PRODUCTS)

        self.YEAR = scenario.YEAR
        self.YEARS = scenario.YEARS

        self.ee_exog = scenario.ee_exog

        # set up params
        param_cols = ['REG_imp','PROD_COMM'] + [c for c in EXOG_VARS.PARAMETERS.columns if ('energy_' in c) & ('energy_hh_' not in c)]
        self.params = EXOG_VARS.PARAMETERS[param_cols].copy()
        self.params.columns = [x.replace("energy_","") for x in self.params.columns]
        param_hh_cols = ['REG_imp','PROD_COMM'] + [c for c in EXOG_VARS.PARAMETERS.columns if ('energy_hh_' in c)]
        self.params_hh = EXOG_VARS.PARAMETERS[param_hh_cols].copy()
        self.params_hh = self.params_hh.drop(columns=['PROD_COMM']).groupby(['REG_imp']).agg('mean').reset_index()
        self.params_hh.columns = [x.replace("energy_hh_","") for x in self.params_hh.columns]

        self.refining_sectors = refining_sectors

        try:
            self.carbon_tax_countries = scenario.carbon_tax_countries
        except AttributeError:
            pass
        
        # read in IEA-energy generated data
        self.ALL_POLLUTANTS = EXOG_VARS.ALL_POLLUTANTS
        self.ALL_PROCESS_EMISSIONS = EXOG_VARS.ALL_PROCESS_EMISSIONS
        self.ALL_FUELS = EXOG_VARS.ALL_FUELS.query("physical_value > 0")

        self.temp = temporary_storage("Temp")

        self.emission_matrix = None
        self.scope1 = None
        self.scope2 = None

    def load_dynamic(self, vars_):
        self.common = {}
        for k,v in vars_.items():
            self.common[k] = v
    
    def init_ener_vars(self):
        self.IEA_eb_sec = 34 # number of flows in IEA
        self.GLORIA_sec = len(self.PRODUCTS) # number of sectors in GLORIA
        self.FD_sec = 6
        
        self.fuel_list_g = ["Coal","Lignite","Oil","Gas","Coke"]
        self.iea_main_fuel = ['COAL','LIGNITE','OIL','GAS','OVENCOKE']
        self.glo_elist_name = ['COAL','LIGNITE','OILExt','GASExt','OVENCOKE','OILRef','GASDis']
        self.IEA_GLORIA_corr=[0,1,2,3,4,2,3]
        
        self.tax_sector_name = ['COAL','LIGNITE','COKE','OIL','GAS']

    def calc_fuel_implicit_price(self):
        # we calculate implict price by flow
        mrio = self.IND_BASE[['REG_imp','REG_exp','PROD_COMM','TRAD_COMM','z_bp']].copy()
        # share of flow within REG_imp / target-sector
        mrio = mrio.astype({'PROD_COMM': 'str'})

        # bring in FD 
        hh_base = self.HH_BASE.rename(columns={'VIPA':'z_bp'}).assign(PROD_COMM = "FD_1")
        fcf_base = self.FCF_BASE.rename(columns={'VDFA':'z_bp'}).assign(PROD_COMM = "FD_4")
        gov_base = self.GOV_BASE.rename(columns={'VIGA':'z_bp'}).assign(PROD_COMM = "FD_3")

        mrio = pd.concat([mrio, hh_base, fcf_base, gov_base])
        fuel_use = self.ALL_FUELS.copy().astype({'PROD_COMM': 'str'})
        fuel_use['PROD_COMM'] = fuel_use['PROD_COMM'].str.replace(".0","")

        mrio = mrio.merge(fuel_use.astype({'PROD_COMM': 'str'}), how='left', on=['REG_imp','REG_exp','PROD_COMM','TRAD_COMM'])
        mrio = mrio[~mrio['physical_value'].isna()]
        # kUSD / TJ
        mrio['implicit_price'] = mrio['z_bp'] / mrio['physical_value']

        # ? the issue here that we found 3/3/2026 is that if the implicit price differs between countries
        # ? and then the trade module drivers trade substitution we might get a situation where physical uses increases
        # ? or decreases substantially just because we're switching to a country (exporter) with a lower/higher implicit price
        # ? therefore our temporary(?) solution is to use a weighted average implicit price
        mrio['share'] = mrio['physical_value'] / mrio.groupby(['REG_imp','PROD_COMM','TRAD_COMM'])['physical_value'].transform('sum')
        mrio['implicit_price'] = mrio['implicit_price'] * mrio['share']
        mrio['implicit_price'] = mrio.groupby(['REG_imp','PROD_COMM','TRAD_COMM'])['implicit_price'].transform('sum')

        return mrio[['REG_imp','REG_exp','PROD_COMM','TRAD_COMM','implicit_price']]


    def calc_fuel_prod_base(self):
        mrio = self.IND_BASE[['REG_imp','REG_exp','PROD_COMM','TRAD_COMM','z_bp']].copy()
        # share of flow within REG_imp / target-sector
        mrio = mrio.astype({'PROD_COMM': 'str'})

        # bring in FD 
        hh_base = self.HH_BASE.rename(columns={'VIPA':'z_bp'}).assign(PROD_COMM = "FD_1")
        fcf_base = self.FCF_BASE.rename(columns={'VDFA':'z_bp'}).assign(PROD_COMM = "FD_4")
        gov_base = self.GOV_BASE.rename(columns={'VIGA':'z_bp'}).assign(PROD_COMM = "FD_3")

        mrio = pd.concat([mrio, hh_base, fcf_base, gov_base])

        mrio = mrio.merge(self.common['fuel_price'].astype({'PROD_COMM': 'str'}), how='left', on=['REG_imp','REG_exp','PROD_COMM','TRAD_COMM'])
        
        # implicit price is : kUSD / TJ
        # fuel_use is : TJ then
        mrio = mrio[~mrio['implicit_price'].isna()]
        mrio['fuel_use'] = np.nan_to_num(mrio['z_bp'] / mrio['implicit_price'], posinf=0, neginf=0, nan=0) # kUSD / kUSD/TJ; $100 
        
        return mrio[['REG_imp','REG_exp','PROD_COMM','TRAD_COMM','fuel_use']].copy()

    def calc_fuel_prod_change(self, dq, q_base):
        # in this function we attach physical units to all GLORIA monetary flows
        # this means that we also calculate implicit prices for the flows
        # we will use this later to keep track of fuel consumption and energy substitution
        fuel_use = self.ALL_FUELS.drop(columns=['REG_imp','PROD_COMM']).groupby(['REG_exp','TRAD_COMM']).agg('sum').reset_index().copy()
        fuel_use = self.MRIO_df_to_vec_DEF(fuel_use.rename(columns={'REG_exp':'REG_imp','TRAD_COMM':'PROD_COMM'}), 'physical_value')
        
        dener = {}
        
        for i in range(len(dq)):
            dener_i = dq[i] / q_base
            dener[i] = dener_i * fuel_use
        return dener.values()
    
    def calc_energy_efficiency(self, energy_flows, output):
        # self.params [['REG_imp','PROD_COMM','energy_total_intensity_l1_ln_price',
        # 'energy_electricity_intensity_L1_relative_price','energy_natural_gas_intensity_L1_relative_price','energy_coal_intensity_L1_relative_price',
        # 'energy_petrol_intensity_L1_relative_price']]

        # self.common['price_index'] is the price index; self.common['delta_price_yoy'] is the change from last year [dp is the var we are looking for]
        # self.E tells us about the energy sector numbers

        # ok, so first overall energy intensity reacts to average weighted price
        # so let's calculate average weighted price
        energy_flows_total = energy_flows.copy()
        # .pipe(lambda d: d[~d['PROD_COMM'].str.contains("FD")]).astype({'PROD_COMM':'int'})
        # ! exclude refining sectors
        energy_flows_total = energy_flows_total.pipe(lambda d: d[~d['PROD_COMM'].isin(self.refining_sectors)]).copy()
        energy_flows_total = energy_flows_total.merge(self.common['delta_price_yoy'].rename(columns={'REG_imp':'REG_exp','PROD_COMM':'TRAD_COMM'}),
                                                      how='left', on=['REG_exp','TRAD_COMM'])
        energy_flows_total = energy_flows_total.merge(self.common['ctax_price_impact'], how='left', on=['REG_imp','PROD_COMM','TRAD_COMM'])

        energy_flows_total['share'] = energy_flows_total['fuel_use'] / energy_flows_total.groupby(['REG_imp','PROD_COMM'])['fuel_use'].transform('sum')

        # exclusions
        energy_flows_total.loc[energy_flows_total['PROD_COMM']==energy_flows_total['TRAD_COMM'], 'dp'] = 0.0
        energy_flows_total.loc[energy_flows_total['PROD_COMM']==energy_flows_total['TRAD_COMM'], 'ctax_price_impact'] = 0.0

        # let's work with real price, i.e., price divided by gdp deflator
        gdp_deflator = self.common['other_vars'][['REG_imp','gdp_deflator']].copy()
        energy_flows_total = energy_flows_total.merge(gdp_deflator, how='left', on=['REG_imp'])
        energy_flows_total['dp'] = (1 + energy_flows_total['dp'] + energy_flows_total['ctax_price_impact']) / (1 + energy_flows_total['gdp_deflator']) - 1.0
        energy_flows_total['dp'] = energy_flows_total['dp'] * energy_flows_total['share']
        energy_flows_total = energy_flows_total.groupby(['REG_imp','PROD_COMM']).agg({'fuel_use':'sum','dp':'sum'}).reset_index()

        # so this is fuel_use by sector and price change by using sector now, but we have the elasticities on energy intensity so we need to correct with output
        energy_flows_total = energy_flows_total.merge(output, how='left', on=['REG_imp','PROD_COMM'])
        energy_flows_total['energy_intensity'] = energy_flows_total['fuel_use'] / energy_flows_total['q_base']

        # ! REVISIT THIS! WHAT OUTPUT REALLY DOES?
        
        # apply elasticity
        energy_flows_total = energy_flows_total.merge(self.params[['REG_imp','PROD_COMM','total_intensity_l1_ln_price']], how='left', on=['REG_imp','PROD_COMM'])
        energy_flows_total['change'] = energy_flows_total['dp'] * energy_flows_total['total_intensity_l1_ln_price']

        # ! LIMIT MAX CHANGE
        energy_flows_total.loc[energy_flows_total['change'] < -0.25, 'change'] = -0.25

        # TODO INTENSITY SHOULD EXCLUDE ENERGY WITH NO PARAMS
        energy_flows_total['energy_intensity_new'] = energy_flows_total['energy_intensity'] * (1 + energy_flows_total['change'])

        # ? adjust with exogenous
        energy_flows_total = energy_flows_total.merge(self.ee_exog, how='left', on=['REG_imp','PROD_COMM'])
        energy_flows_total['ee_change'] = energy_flows_total['ee_change'].fillna(0)
        energy_flows_total['energy_intensity_new'] = energy_flows_total['energy_intensity_new'] * (1+energy_flows_total['ee_change'])

        # calculate demand effects
        energy_flows_total['fuel_use_total'] = energy_flows_total['energy_intensity_new'] * energy_flows_total['q_base']

        self.delta_efficiency = energy_flows_total[['REG_imp','PROD_COMM','fuel_use_total']].copy()

    def calc_fuel_substitution(self, energy_flows, output, output_prev):

        # ! MIGHT NEED TO REVIEW that we're working with dp, should change to price_index?
        # ok, so we've calculated the price response, but keep in mind that we might have more reallocation across fuels (i.e., that is the net effect)
        # so let's see what effect the prices have on fuel allocation
        energy_flows_substitution = energy_flows.copy()
        # .pipe(lambda d: d[~d['PROD_COMM'].str.contains("FD")]).astype({'PROD_COMM':'int'})
        # ! exclude refining sectors
        energy_flows_substitution = energy_flows_substitution.pipe(lambda d: d[~d['PROD_COMM'].isin(self.refining_sectors)]).copy()
        energy_flows_substitution = energy_flows_substitution.merge(self.common['delta_price_yoy'].rename(columns={'REG_imp':'REG_exp','PROD_COMM':'TRAD_COMM','dp':'delta_price_yoy'}), how='left', on=['REG_exp','TRAD_COMM'])
        energy_flows_substitution = energy_flows_substitution.merge(self.common['ctax_price_impact'], how='left', on=['REG_imp','PROD_COMM','TRAD_COMM'])
        
        # ! no substitution to own
        energy_flows_substitution.loc[energy_flows_substitution['PROD_COMM']==energy_flows_substitution['TRAD_COMM'], 'delta_price_yoy'] = 0.0
        energy_flows_substitution.loc[energy_flows_substitution['PROD_COMM']==energy_flows_substitution['TRAD_COMM'], 'ctax_price_impact'] = 0.0
        # ! no substitution signal from dead fuel sectors (fuel_use == 0 means z_bp was
        # already zeroed in IND_BASE, e.g. coal died last year and IND_BASE was cleaned).
        # Without this guard, NaN component_shares propagate through the calculation and
        # can produce non-zero fuel_use_change_relative even when there is no actual flow.
        energy_flows_substitution.loc[energy_flows_substitution['fuel_use'] == 0, 'delta_price_yoy'] = 0.0
        energy_flows_substitution.loc[energy_flows_substitution['fuel_use'] == 0, 'ctax_price_impact'] = 0.0

        # ! we also want to keep shares intact across coal/petrol/gas types
        params_price = self.params[[x for x in self.params.columns if '_price' in str(x)] + ['REG_imp','PROD_COMM']].copy()
        params_output = self.params[[x for x in self.params.columns if '_output' in str(x)] + ['REG_imp','PROD_COMM']].copy()

        sectors_ = {}
        sectors_['naturalgas'] = self.E[self.E['Sector_names'].str.contains("gas|Gas")]['Lfd_Nr'].to_list()
        sectors_['coal'] = self.E[self.E['Sector_names'].str.contains("coal|Coke|Coal|coke")]['Lfd_Nr'].to_list()
        sectors_['lignite'] = self.E[self.E['Sector_names'].str.contains("lignite|Lignite")]['Lfd_Nr'].to_list()
        sectors_['petrol'] = self.E[self.E['Sector_names'].str.contains("petroleum|Petroleum")]['Lfd_Nr'].to_list()
        sectors_['electricity'] = self.E[self.E['Sector_names'].str.contains("Electric|electric")]['Lfd_Nr'].to_list()

        energy_flows_substitution['fuel'] = "NA"
        
        for k, secs in sectors_.items():
            for s in secs:
                energy_flows_substitution.loc[energy_flows_substitution['TRAD_COMM']==s, 'fuel'] = k
        
        energy_flows_substitution['component_share'] = energy_flows_substitution['fuel_use'] / energy_flows_substitution.groupby(['REG_imp','REG_exp','PROD_COMM','fuel'])['fuel_use'].transform('sum')
        component_shares = energy_flows_substitution[['REG_imp','REG_exp','PROD_COMM','TRAD_COMM','fuel','component_share']].copy()

        # ? aggregate for fuel
        energy_flows_substitution['delta_price_yoy_fuel'] = energy_flows_substitution['delta_price_yoy'] * energy_flows_substitution['component_share']
        energy_flows_substitution['ctax_price_impact'] = energy_flows_substitution['ctax_price_impact'] * energy_flows_substitution['component_share']
        # weighted average for others than fuel use
        energy_flows_substitution = energy_flows_substitution.groupby(['REG_imp','REG_exp','PROD_COMM','fuel']).agg({'delta_price_yoy_fuel':'sum','ctax_price_impact':'sum','fuel_use':'sum'}).reset_index()

        energy_flows_substitution['share_in_total'] = energy_flows_substitution['fuel_use'] / energy_flows_substitution.groupby(['REG_imp','PROD_COMM'])['fuel_use'].transform('sum')
        energy_flows_substitution['delta_price_yoy_avg'] = (energy_flows_substitution['delta_price_yoy_fuel'] + energy_flows_substitution['ctax_price_impact'])* energy_flows_substitution['share_in_total']
        energy_flows_substitution['delta_price_yoy_avg'] = energy_flows_substitution.groupby(['REG_imp','PROD_COMM'])['delta_price_yoy_avg'].transform('sum')

        # ? aggregate across trade partners
        energy_flows_substitution['share_in_fuel'] = energy_flows_substitution['fuel_use'] / energy_flows_substitution.groupby(['REG_imp','PROD_COMM','fuel'])['fuel_use'].transform('sum')
        trade_shares = energy_flows_substitution[['REG_imp','REG_exp','PROD_COMM','fuel','share_in_fuel']].copy()
        energy_flows_substitution['delta_price_yoy_avg_fuel'] = (energy_flows_substitution['delta_price_yoy_fuel']+ energy_flows_substitution['ctax_price_impact']) * energy_flows_substitution['share_in_fuel']
        # energy_flows_substitution['delta_price_yoy_avg_fuel'] = energy_flows_substitution.groupby(['REG_imp','PROD_COMM','fuel'])['delta_price_yoy_avg_fuel'].transform('sum')

        # use 'mean' here as aggregate because values should be identical across the group
        energy_flows_substitution = energy_flows_substitution.groupby(['REG_imp','PROD_COMM','fuel']).agg({'delta_price_yoy_avg':'mean','delta_price_yoy_avg_fuel':'sum','fuel_use':'sum'}).reset_index()
        
        # now we have price change and stuff, let's add output and coefficients
        energy_flows_substitution = energy_flows_substitution.merge(output, how='left', on=['REG_imp','PROD_COMM'])
        energy_flows_substitution = energy_flows_substitution.merge(output_prev, how='left', on=['REG_imp','PROD_COMM'])

        # TJ / kUSD
        # energy_flows_substitution['fuel_intensity'] = energy_flows_substitution['fuel_use'] / energy_flows_substitution['q_base']

        # self.params [['REG_imp','PROD_COMM','energy_total_intensity_l1_ln_price',
        # 'energy_electricity_intensity_L1_relative_price','energy_naturalgas_intensity_L1_relative_price','energy_coal_intensity_L1_relative_price',
        # 'energy_petrol_intensity_L1_relative_price']]

        # ? let's figure out sector numbers for each of the energy types
        # gas|Gas
        # coal|Coke|Coal|coke|lignite|Lignite
        # petroleum|Petroleum
        # Electric|electric

        # TODO we're switching between the different coal types and petrol types and natural gas types if there relative prices are different
        # TODO we shouldn't do this 

        params_price = pd.melt(params_price, id_vars=['REG_imp','PROD_COMM'], value_name='relative_price_beta', var_name='fuel')
        params_price['fuel'] = params_price['fuel'].str.partition("_")[0]

        params_output = pd.melt(params_output, id_vars=['REG_imp','PROD_COMM'], value_name='output_beta', var_name='fuel')
        params_output['fuel'] = params_output['fuel'].str.partition("_")[0]

        # ? 'total' is in fuel too, but that will get left out with left merge anyway

        # let's merge the param table
        energy_flows_substitution = energy_flows_substitution.merge(params_price, how='left', on=['REG_imp','PROD_COMM','fuel'])
        energy_flows_substitution['relative_price_beta'] = energy_flows_substitution['relative_price_beta'].fillna(0)
        energy_flows_substitution = energy_flows_substitution.merge(params_output, how='left', on=['REG_imp','PROD_COMM','fuel'])
        energy_flows_substitution['output_beta'] = energy_flows_substitution['output_beta'].fillna(0)

        # use price index to calculate relative price change
        energy_flows_substitution['relative_change_price'] = (1 + energy_flows_substitution['delta_price_yoy_avg_fuel']) / (1 + energy_flows_substitution['delta_price_yoy_avg']) - 1.0
        energy_flows_substitution['relative_change_output'] = energy_flows_substitution['q_base'] / energy_flows_substitution['q_prev'] - 1.0

        #### TJ
        energy_flows_substitution['fuel_use_new'] = energy_flows_substitution['fuel_use']\
              * (1 + energy_flows_substitution['relative_change_price'] * energy_flows_substitution['relative_price_beta'])\
              * (1 + energy_flows_substitution['relative_change_output'] * energy_flows_substitution['output_beta'])
        
        # impact is in fuel intensity change

        # we need to match this to the aggregate
        # self.delta_efficiency

        energy_flows_substitution = energy_flows_substitution[['REG_imp','PROD_COMM','fuel','fuel_use_new','fuel_use', 'relative_price_beta', 'output_beta']].merge(self.delta_efficiency, 
                                                                                                        how='left', on=['REG_imp','PROD_COMM'])
        
        energy_flows_substitution['fuel_use_total'] = energy_flows_substitution['fuel_use_total'].fillna(0)
        
        # can use mean, bc value is the same across
        # ? fuel_use_total is total fuel use (TJ) after energy efficiency; fuel_use_new is calculated based on fuel changes; we want the two to match
        # DON'T MULTIPLY FUEL x SECTOR COMBINATIONS WHERE PARAMETER IS 0!!!!!!!!!!!!!!!!!!!
        energy_flows_substitution['fuel_use2'] = energy_flows_substitution['fuel_use']
        # ! remove cases where parameters are zero, no REG_exp here
        mask = (energy_flows_substitution['relative_price_beta'] == 0) & (energy_flows_substitution['output_beta'] == 0)
        energy_flows_substitution.loc[mask, 'fuel_use'] = 0.0
        energy_flows_substitution.loc[mask, 'fuel_use_new'] = 0.0
        energy_flows_substitution.loc[~mask, 'fuel_use2'] = 0.0

        energy_flows_substitution['fuel_use_total'] = energy_flows_substitution['fuel_use_total'] - energy_flows_substitution.groupby(['REG_imp','PROD_COMM'])['fuel_use2'].transform('sum')

        agg = energy_flows_substitution.groupby(['REG_imp', 'PROD_COMM']).agg(
            fuel_use_per_sector_before=('fuel_use', 'sum'),
            fuel_use_per_sector_after=('fuel_use_new', 'sum'),
            fuel_use_per_sector_after_efficiency=('fuel_use_total', 'mean')
        ).reset_index()
        
        energy_flows_substitution = energy_flows_substitution.merge(agg, on=['REG_imp', 'PROD_COMM'], how='left')

        before = energy_flows_substitution['fuel_use_per_sector_before']
        after = energy_flows_substitution['fuel_use_per_sector_after']
        after_eff = energy_flows_substitution['fuel_use_per_sector_after_efficiency']

        # ? we assume that everything changes the same, due to efficiency at this point
        # ? fuel_use_per_sector_delta - fuel_use_per_sector_before ---> efficiency change (1net change)
        # ? fuel_use_per_sector_after - fuel_use_per_sector_before ---> fuel-level changes 
        
        energy_flows_substitution['fuel_use_after_efficiency'] = energy_flows_substitution['fuel_use'] * (np.nan_to_num(after_eff / before, nan=0, posinf=0, neginf=0)) # fuel-level

        # ? now introduce the substitution
        energy_flows_substitution['fuel_use_new_adj'] = energy_flows_substitution['fuel_use_new'] * (np.nan_to_num(after_eff / after, nan=0, posinf=0, neginf=0))
        # ? add back non-changed fuels
        energy_flows_substitution['fuel_use_new_adj'] = energy_flows_substitution['fuel_use_new_adj'] + energy_flows_substitution['fuel_use2']
        # calc change
        energy_flows_substitution['fuel_use_change'] = energy_flows_substitution['fuel_use_new_adj'] - (energy_flows_substitution['fuel_use'] + energy_flows_substitution['fuel_use2'])

        # ! reinstate trade partners
        energy_flows_substitution = energy_flows_substitution.merge(trade_shares, how='left', on=['REG_imp','fuel','PROD_COMM'])
        energy_flows_substitution['fuel_use_change'] = energy_flows_substitution['fuel_use_change'] * energy_flows_substitution['share_in_fuel']
        energy_flows_substitution['fuel_use_new_adj'] = (energy_flows_substitution['fuel_use'] + energy_flows_substitution['fuel_use2'] + energy_flows_substitution['fuel_use_change']) * energy_flows_substitution['share_in_fuel'] 

        # ! reinstate components (TRAD_COMM)
        energy_flows_substitution = energy_flows_substitution.merge(component_shares, how='left', on=['REG_imp','REG_exp','PROD_COMM','fuel'])
        energy_flows_substitution['fuel_use_change'] = energy_flows_substitution['fuel_use_change'] * energy_flows_substitution['component_share']
        energy_flows_substitution['fuel_use_new_adj'] = (energy_flows_substitution['fuel_use_new_adj']) * energy_flows_substitution['component_share']

        # calculate monetary
        # energy_flows_substitution = energy_flows_substitution.merge(self.common['fuel_price'].pipe(lambda d: d[~d['PROD_COMM'].str.contains("FD")]).astype({'PROD_COMM':'int'})
                                                                    # , how='left', on=['REG_imp','REG_exp','PROD_COMM','TRAD_COMM'])
        # kUSD / TJ -> implicit_price
        # fueluse -> TJ
        energy_flows_substitution['fuel_use_change_relative'] =  np.nan_to_num(energy_flows_substitution['fuel_use_change'] / energy_flows_substitution['fuel_use'],nan=0,posinf=0,neginf=0) # TJ * kUSD/TJ

        return {
            'energy_flows': energy_flows_substitution[['REG_imp','REG_exp','PROD_COMM','TRAD_COMM','fuel_use_new_adj']].copy(),
            'io_impact': energy_flows_substitution[['REG_imp','REG_exp','PROD_COMM','TRAD_COMM','fuel_use_change_relative']].copy()
        }
    
    def hh_fuel_substitution(self, energy_flows, hh_cons, hh_cons_prev, hh_price):
        # ? hh substitution across energy carriers
        # ! NOTE: we only do substitution here, because own price elasticity
        # ! is in the HH module, so overall value of energy (constant price)
        # ! shouldn't change going out of this module
        # hh_cons is REG_imp | REG_exp | TRAD_COMM | VIPA
        # hh_price is REG_imp | TRAD_COMM | delta_p_avg | VIPA_prod

        # calc tech shares in HH consumption
        hh = hh_cons.reset_index()
        hh = hh[hh['TRAD_COMM'].isin(self.ENERGY_LIST)].copy()

        hh_prev = hh_cons_prev.reset_index().rename(columns={'VIPA':'VIPA_prev'})
        hh_prev = hh_prev[hh_prev['TRAD_COMM'].isin(self.ENERGY_LIST)].copy()

        hh = hh.merge(hh_prev, how="outer").fillna(10)

        # fuel price
        fuel_price = self.common['fuel_price'].query("PROD_COMM == 'FD_1'").drop(columns=['PROD_COMM'])
        hh = hh.merge(fuel_price, how='left', on=['REG_imp','REG_exp','TRAD_COMM'])

        hh['physical_value'] = np.nan_to_num(hh['VIPA'] / hh['implicit_price'], nan=0.0, posinf=0.0, neginf=0.0) # kUSD/TJ --> we want TJ
        
        hh_ = hh.copy()

        hh = hh.groupby(['REG_imp','TRAD_COMM']).agg({'physical_value':'sum','VIPA':'sum','VIPA_prev':'sum'}).reset_index()
        hh['share'] = hh['physical_value'] / hh.groupby(['REG_imp'])['physical_value'].transform('sum')

        # in price we don't know the source anymore, that's fine
        price = hh_price[hh_price['TRAD_COMM'].isin(self.ENERGY_LIST)].copy()
        price = price[['REG_imp','TRAD_COMM','delta_p_avg']].copy()
        price['price_d'] = np.nan_to_num(price['delta_p_avg'] - price.groupby(['REG_imp'])['delta_p_avg'].transform('mean'), nan=1.0)
        # ? HH price already includes carbon tax!
        # TODO is this true?
        hh = hh.merge(price, how='left', on=['REG_imp','TRAD_COMM'])

        params_price = self.params_hh[[x for x in self.params_hh.columns if '_price' in str(x)] + ['REG_imp']].copy()
        params_output = self.params_hh[[x for x in self.params_hh.columns if '_income' in str(x)] + ['REG_imp']].copy()

        sectors_ = {}
        sectors_['naturalgas'] = self.E[self.E['Sector_names'].str.contains("gas|Gas")]['Lfd_Nr'].to_list()
        sectors_['coal'] = self.E[self.E['Sector_names'].str.contains("coal|Coke|Coal|coke")]['Lfd_Nr'].to_list()
        sectors_['lignite'] = self.E[self.E['Sector_names'].str.contains("lignite|Lignite")]['Lfd_Nr'].to_list()
        sectors_['petrol'] = self.E[self.E['Sector_names'].str.contains("petroleum|Petroleum")]['Lfd_Nr'].to_list()
        sectors_['electricity'] = self.E[self.E['Sector_names'].str.contains("Electric|electric")]['Lfd_Nr'].to_list()

        for k, secs in sectors_.items():
            for s in secs:
                params_price[s] = params_price['{}_intensity_L1_relative_price'.format(k)]
                params_output[s] = params_output['{}_intensity_L1_income'.format(k)]

        params_price = params_price[[x for x in params_price.columns if '_price' not in str(x)]].copy()
        params_price = pd.melt(params_price, id_vars=['REG_imp'], value_name='relative_price_beta', var_name='TRAD_COMM')

        params_output = params_output[[x for x in params_output.columns if '_income' not in str(x)]].copy()
        params_output = pd.melt(params_output, id_vars=['REG_imp'], value_name='income_beta', var_name='TRAD_COMM')

        # let's merge the param table
        hh = hh.merge(params_price, how='left', on=['REG_imp','TRAD_COMM'])
        hh['relative_price_beta'] = hh['relative_price_beta'].fillna(0)
        hh = hh.merge(params_output, how='left', on=['REG_imp','TRAD_COMM'])
        hh['income_beta'] = hh['income_beta'].fillna(0)

        hh['relative_price'] = np.nan_to_num((1 + hh['price_d']) / (1 + hh['share'] * hh['price_d']) - 1, nan=0.0, posinf=0, neginf=0)
        hh['spent'] = np.nan_to_num(hh['VIPA'] / hh['VIPA_prev'] - 1.0, nan=0.0, posinf=0, neginf=0)
        
        #### TJ
        hh['physical_value_new'] = hh['physical_value']\
              * (1 + hh['relative_price'] * hh['relative_price_beta'])\
              * (1 + hh['spent'] * hh['income_beta'])

        hh['physical_value_adjust'] = hh.groupby(['REG_imp'])['physical_value'].transform('sum') / hh.groupby(['REG_imp'])['physical_value_new'].transform('sum')
        hh['physical_value_new_adj'] = hh['physical_value_new'] * hh['physical_value_adjust']
        hh['physical_value_imp'] = hh['physical_value_new_adj'] - hh['physical_value']

        # allocate across export partners
        hh_['exp_share'] = hh_['physical_value'] / hh_.groupby(['REG_imp','TRAD_COMM'])['physical_value'].transform('sum')
        hh_ = hh_[['REG_imp','TRAD_COMM','REG_exp','exp_share']].copy()

        hh = hh.merge(hh_, how='left', on=['REG_imp','TRAD_COMM'])
        hh['physical_value_imp'] = hh['physical_value_imp'] * hh['exp_share']

        hh = hh[['REG_imp','REG_exp','TRAD_COMM','physical_value_imp']].merge(fuel_price, how='left', on=['REG_imp','REG_exp','TRAD_COMM'])
        hh['VIPA_imp'] = np.nan_to_num(hh['physical_value_imp'] * hh['implicit_price'], nan=0.0, posinf=0.0, neginf=0.0)

        return hh.drop(columns=['physical_value_imp','implicit_price']).fillna(0)
    
    def calc_monetary_io_change(self, io_impact):
        df = self.IND_BASE.merge(io_impact, how='left', on=['REG_imp','REG_exp','PROD_COMM','TRAD_COMM'])
        df['fuel_use_change_relative'] = df['fuel_use_change_relative'].fillna(0)
        df['z_bp_ener'] = df['z_bp'] * (1+df['fuel_use_change_relative'])
        df.loc[df['z_bp_ener'] < 0, 'z_bp_ener'] = 0.0
        df['IO_coef_ener'] = df['z_bp_ener'] / df['output']

        df = df.set_index(['REG_imp','REG_exp','PROD_COMM','TRAD_COMM'])

        return df[['z_bp_ener','IO_coef_ener']].copy()

    def calc_emission_intensities(self):
        emissions = self.ALL_POLLUTANTS.pipe(lambda d: d[d['POLLUTANT_FRACTION']=='CO2']).copy()
         # ! mixed variable need to get rid of .0
        emissions['target-sector'] = emissions['target-sector'].apply(lambda x: x.replace(".0", ""))

        mrio = self.IND_BASE.drop(columns=['a_bp','a_tech','output']).copy()
        # share of flow within REG_imp / target-sector
        mrio = mrio.astype({'PROD_COMM': 'str'})

        # bring in FD 
        hh_base = self.HH_BASE.rename(columns={'VIPA':'z_bp'}).assign(PROD_COMM = "FD_1")
        fcf_base = self.FCF_BASE.rename(columns={'VDFA':'z_bp'}).assign(PROD_COMM = "FD_4")
        gov_base = self.GOV_BASE.rename(columns={'VIGA':'z_bp'}).assign(PROD_COMM = "FD_3")

        mrio = pd.concat([mrio, hh_base, fcf_base, gov_base])

        emission_intensity =  mrio[['REG_imp','PROD_COMM','REG_exp','TRAD_COMM','z_bp']]\
            .merge(emissions.rename(columns={'target-country-iso3':'REG_imp','target-sector':'PROD_COMM',
                                             'origin-country-iso3':'REG_exp','origin-sector':'TRAD_COMM'}
                                             ).astype({'PROD_COMM':'str'}), how='left')
        # ktCO2 / kUSD
        # POLLUTANT value in tonnes; z_bp in kUSD
        emission_intensity['EF_ktCO2_per_kUSD'] = (emission_intensity['POLLUTANT_VALUE'] / 1000) / emission_intensity['z_bp']
        emission_intensity = emission_intensity.fillna(0)

        return(emission_intensity[['REG_imp','PROD_COMM','REG_exp','TRAD_COMM','EF_ktCO2_per_kUSD']].copy())
    
    def calc_emission_intensities_process(self):
        # calculate process emissions
        # target-sector	target-country-iso3	Y_2019	output_kUSD	EF_ktCO2_per_kUSD
        process_emissions = self.ALL_PROCESS_EMISSIONS[['target-sector','target-country-iso3','EF_ktCO2_per_kUSD']].copy()
        process_emissions['target-sector'] = process_emissions['target-sector'].astype(str)
        process_emissions = process_emissions.rename(columns={'target-sector':'PROD_COMM','target-country-iso3':'REG_imp'})

        default_process_emissions = process_emissions[process_emissions['REG_imp']=='DEFAULT'].copy()
        default_process_emissions = default_process_emissions.rename(columns={'EF_ktCO2_per_kUSD':'def_EF_ktCO2_per_kUSD'})

        # DEFAULT values are need to be added for missing emission rates
        process_emissions = process_emissions.merge(default_process_emissions.drop(columns=['REG_imp']), how='left', on=['PROD_COMM'])
        sel = np.isnan(process_emissions['EF_ktCO2_per_kUSD'])
        process_emissions.loc[sel, 'EF_ktCO2_per_kUSD'] = process_emissions.loc[sel, 'def_EF_ktCO2_per_kUSD']
        process_emissions = process_emissions.drop(columns=['def_EF_ktCO2_per_kUSD'])
        del default_process_emissions 
        
        return(process_emissions[['REG_imp','PROD_COMM','EF_ktCO2_per_kUSD']].copy())

    def update_ind_base(self, A_trade, output):
        ind_base = A_trade * output
        ind_base = MRIO_mat_to_df(ind_base, len(self.P_list), self.REGION)\
            .rename(columns={'target-country-iso3':'REG_imp','origin-country-iso3':'REG_exp'})
        ind_base = ind_base.drop(columns=['target-country','origin-country']).rename(columns={'value':'z_bp'})
        self.IND_BASE = ind_base
        
    def read_tax_incidence(self, tax_incidence_file):
        tmp_ = None
        tmp_ = pd.read_csv(tax_incidence_file)

        return tmp_
    
    def tax_incidence_loop(self, country):
        """
        This loop calculates the tax incidence given carbon_tax_rate files generated
        by earlier functions (these are stored in the Temp folder).
        This loop is only expected to be run within the `calculate_tax_incidence` function
        in a parallel loop.
        """
        carbon_tax_rate = self.temp.read_from_pickle("carbon_tax_rate", delete_=False).pipe(lambda d: d[d['REG_imp']==country])
        carbon_content = self.common['carbon_content'].pipe(lambda d: d[(d['REG_imp'] == country)])
        # calculate emission cost per flow

        carbon_tax_rate = carbon_tax_rate.pipe(lambda d: d[~d['ctax'].isna()])
        carbon_tax_rate = carbon_tax_rate.astype({'PROD_COMM':'str','TRAD_COMM':'str'})

        mrio = self.IND_BASE[(self.IND_BASE['REG_imp']==country)][['REG_imp','REG_exp','PROD_COMM','TRAD_COMM','z_bp']].copy()
        # share of flow within REG_imp / target-sector
        mrio = mrio.astype({'TRAD_COMM': 'int', 'PROD_COMM': 'str'})

        # bring in FD 
        hh_base = self.HH_BASE.rename(columns={'VIPA':'z_bp'}).assign(PROD_COMM = "FD_1")
        fcf_base = self.FCF_BASE.rename(columns={'VDFA':'z_bp'}).assign(PROD_COMM = "FD_4")
        gov_base = self.GOV_BASE.rename(columns={'VIGA':'z_bp'}).assign(PROD_COMM = "FD_3")
        # now it has REG_imp | PROD_COMM | REG_exp | TRAD_COMM | z_bp

        mrio = pd.concat([mrio, hh_base, fcf_base, gov_base])
        # price intermediate flows - combustion ONLY
        emission_cost = mrio.merge(carbon_content, on=['REG_imp','PROD_COMM','TRAD_COMM','REG_exp'], how='left')
        # ktCO2 emissions, based on z_bp (real value) and EF (which is ktco2 per kusd, real price)
        emission_cost['emission_ktco2'] = emission_cost['z_bp'] * emission_cost['EF_ktCO2_per_kUSD']

        emission_cost = emission_cost[(emission_cost['emission_ktco2'] > 0)]
        emission_cost = emission_cost.fillna(0)

        emission_cost = emission_cost.merge(carbon_tax_rate.astype({'PROD_COMM':'str','TRAD_COMM':'int'}), how='left', on=['REG_imp','PROD_COMM','REG_exp','TRAD_COMM'])
        emission_cost = emission_cost[~emission_cost['ctax'].isna()]
        
        emission_cost['emission_cost'] = emission_cost['emission_ktco2'] * emission_cost['ctax'] 
        # emission in ktCO2, ctax in USD/tCO2; and we want results in kUSD
        emission_cost = emission_cost[['REG_imp','PROD_COMM','REG_exp','TRAD_COMM','emission_cost','z_bp']].copy()

        emission_cost = emission_cost[~emission_cost['emission_cost'].isna()]
        emission_cost = emission_cost[emission_cost['emission_cost']!=0]

        return emission_cost

    def calculate_tax_incidence(self):

        # do for countries with carbon tax
        carbon_tax_countries = self.carbon_tax_countries
        if len(carbon_tax_countries) == 0:
            df = pd.DataFrame(columns=['REG_imp','PROD_COMM','REG_exp','TRAD_COMM','emission_cost'])
            df2 = pd.DataFrame(columns=['REG_imp','PROD_COMM','REG_exp','TRAD_COMM','flow_price_impact'])
        
            result = {
                'tax_incidence_intermediates': df,
                'flow_price_impact_intermediates': df2.rename(columns={'flow_price_impact':'flow_price_impact_intermediates'}),
                'tax_incidence_hh': df,
                'flow_price_impact_hh': df2.rename(columns={'flow_price_impact':'flow_price_impact_hh'}),
                'tax_incidence_fcf': df,
                'tax_incidence_gov': df
            }

            return(result)

        tax_incidence_all = None
        
        # print("Calculating tax incidence... Parallel started.")
        # with alive_bar(len(tax_rate['REG_imp'].unique()), title="Generating carbon tax files...") as bar:

        # non-parallel for debugging
        # tmp_df = []
        # for c in carbon_tax_countries:
        #     tmp_df.append(self.tax_incidence_loop(c))
        # tax_incidence_all = pd.concat(tmp_df)
        
        futures_ = [] 
        with futures.ThreadPoolExecutor() as executor:
            for c in carbon_tax_countries:
                futures_.append(executor.submit(self.tax_incidence_loop, c))
        
            tmp_df = []
            # with tqdm(total=len(futures_)) as progress:
            for f in futures.as_completed(futures_):
                    # progress.update()
                tmp_df.append(f.result())
            tax_incidence_all = pd.concat(tmp_df)

            # results = list(tqdm(executor.map(self.tax_incidence_loop, carbon_tax_countries), 
                    #   total=len(carbon_tax_countries)))
        print("Completed.")

        tax_incidence_all_1 = tax_incidence_all[['REG_imp','PROD_COMM','REG_exp','TRAD_COMM','emission_cost']].copy()
        tax_incidence_all_1 = tax_incidence_all_1.groupby(['REG_imp','PROD_COMM','REG_exp','TRAD_COMM']).agg({'emission_cost':'sum'}).reset_index()
        # self.temp.write_to_csv(tax_incidence_all, 'tax_incidence_all')

        tax_incidence_intermediates = tax_incidence_all_1[~(tax_incidence_all_1['PROD_COMM'].str.contains("FD"))].copy()
        tax_incidence_intermediates = tax_incidence_intermediates.astype({'PROD_COMM':'int'})
        tax_incidence_hh = tax_incidence_all_1[tax_incidence_all_1['PROD_COMM']=='FD_1'].copy()
        tax_incidence_fcf = tax_incidence_all_1[tax_incidence_all_1['PROD_COMM']=='FD_4'].copy()
        tax_incidence_gov = tax_incidence_all_1[tax_incidence_all_1['PROD_COMM']=='FD_3'].copy()

        tax_incidence_all_2 = tax_incidence_all[['REG_imp','PROD_COMM','REG_exp','TRAD_COMM','emission_cost','z_bp']].copy()
        tax_incidence_all_2 = tax_incidence_all_2.groupby(['REG_imp','PROD_COMM','TRAD_COMM']).agg({'emission_cost':'sum','z_bp':'sum'}).reset_index()
        tax_incidence_all_2['flow_price_impact'] = tax_incidence_all_2['emission_cost'] / tax_incidence_all_2['z_bp']
        tax_incidence_all_2 = tax_incidence_all_2.drop(columns=['emission_cost','z_bp'])
        # self.temp.write_to_csv(tax_incidence_all, 'tax_incidence_all')

        tax_incidence_intermediates_2 = tax_incidence_all_2[~(tax_incidence_all_2['PROD_COMM'].str.contains("FD"))].copy()
        tax_incidence_intermediates_2 = tax_incidence_intermediates_2.astype({'PROD_COMM':'int'}).rename(columns={'flow_price_impact':'flow_price_impact_intermediates'})
        tax_incidence_hh_2 = tax_incidence_all_2[tax_incidence_all_2['PROD_COMM']=='FD_1'].copy().rename(columns={'flow_price_impact':'flow_price_impact_hh'})

        result = {
            'tax_incidence_intermediates': tax_incidence_intermediates,
            'tax_incidence_hh': tax_incidence_hh,
            'tax_incidence_fcf': tax_incidence_fcf,
            'tax_incidence_gov': tax_incidence_gov,
            'flow_price_impact_intermediates': tax_incidence_intermediates_2,
            'flow_price_impact_hh': tax_incidence_hh_2
        }

        return(result)
    
    def MRIO_mat_to_df(self, MRIO):
        # MRIO is 19680 x 19680 matrix, this is 120x164, 120x164   

        # 1. put into dataframe
        mrio = pd.DataFrame(MRIO).reset_index()

        # now we have 
        # columns: index [sec1-reg1 = 0] [sec2-reg1 = 1] ... [sec120 - reg164 = 19680]
        # rows: 1 2 3 ... 19680

        # 2. melt
        mrio = pd.melt(mrio, id_vars=['index'])
        # now it's
        # columns: index[==row-index] variable[==column-index] value
        # rows: 1 2 3 ... 19680

        # 3. reindex
        mrio['origin-country'] = np.floor(mrio['index'] / len(self.PRODUCTS))
        mrio['origin-sector'] = mrio['index'] % len(self.PRODUCTS)
        mrio['target-country'] = np.floor(mrio['variable'] / len(self.PRODUCTS))
        mrio['target-sector'] = mrio['variable'] % len(self.PRODUCTS)

        # 4. merge country-iso
        mrio = self.attach_iso3(mrio, self.REGION)
        
        return mrio
    
    def attach_iso3(df, regions):
        """ 
        Attaches ISO3 codes from the `regions` input to the dataframe
        `origin-country` and `target-country` have to be present in the dataframe
        """
        df = df.merge(regions, how='left', left_on=['target-country'], right_on=['Lfd_Nr']).rename(columns={'Region_acronyms':'target-country-iso3'})\
            .drop(columns=['Region_names','Lfd_Nr'])
        df = df.merge(regions, how='left', left_on=['origin-country'], right_on=['Lfd_Nr']).rename(columns={'Region_acronyms':'origin-country-iso3'})\
            .drop(columns=['Region_names','Lfd_Nr'])
        return df
    
    def build_emission_matrix(self, pollutants_df, pollutant_fraction):
        pollutants_df = pollutants_df[pollutants_df['POLLUTANT_FRACTION']==pollutant_fraction].copy()
        pollutants_df = pollutants_df[["target-country-iso3","origin-country-iso3","target-sector","origin-sector","POLLUTANT_VALUE"]].copy()
        pollutants_df = pollutants_df[~pollutants_df['target-sector'].str.contains('FD')].copy()
        pollutants_df['target-sector'] = pollutants_df['target-sector'].astype('float').astype('int16')
        pollutants_df['origin-sector'] = pollutants_df['origin-sector'].astype('float').astype('int16')
        pollutants_df = pollutants_df.groupby(['origin-country-iso3','target-country-iso3','origin-sector','target-sector']).agg({'POLLUTANT_VALUE':'sum'}).reset_index()
        pollutants_df['row_index'] = tuple(zip(pollutants_df['origin-country-iso3'], pollutants_df['origin-sector']))
        pollutants_df['col_index'] = tuple(zip(pollutants_df['target-country-iso3'], pollutants_df['target-sector']))
        
        pollutants_df = pollutants_df.set_index(['row_index','col_index'])['POLLUTANT_VALUE'].unstack('col_index').fillna(0)
        p_temp = pd.DataFrame(np.zeros((self.DIMS,self.DIMS)), index=self.A_id, columns=self.A_id)
        p_temp.loc[pollutants_df.index, pollutants_df.columns] = pollutants_df.values

        POLLUTANTS_BASE = p_temp.to_numpy()
        
        return POLLUTANTS_BASE
        
    def delta_emissions(self, deltaQ, MRIO_current, MRIO_initial, q_base):
        """
        Function to calculate delta emissions given a 19680 (120*164) vector of output change across the MRIO and
        current MRIO state (A_trade).
        """

        # both MRIO is 19680 x 19680 matrix, this is 120x164, 120x164
        # deltaQ is singel 19680

        # create all pollutants matrix
        # ! ONLY CO2 for now
        all_pollutants = self.ALL_POLLUTANTS

        # ! replace inf with 0.0, th NO new sectors
        current = MRIO_current * (deltaQ + q_base)
        initial_base = MRIO_initial * q_base
        step1 = np.nan_to_num(np.divide(current, initial_base) - 1)
        del current
        del initial_base
        gc.collect()
        # print('step1')
        
        emission_matrix = self.build_emission_matrix(self.ALL_POLLUTANTS, 'CO2')
        step2 = np.multiply(step1, emission_matrix)
        del emission_matrix
        del step1
        gc.collect()

        dEmissions = step2.sum(axis=0)
        # supposed to be a 19680 vector

        # now process it into DF
        df = pd.DataFrame({
            'dEmissions': dEmissions,
            'dQ': deltaQ,
            'q_base': q_base 
            }).reset_index()
        df['target-sector'] = df['index'] % len(self.PRODUCTS) + 1
        df['target-country'] = np.floor(df['index'] / len(self.PRODUCTS)) + 1

        # Lfd_Nr	Region_acronyms	Region_names
        df = df.merge(self.REGION.rename(columns={'Lfd_Nr':'target-country'}), how='left', on='target-country')
        df = df.rename(columns={'Region_acronyms':'target-country-iso3'}).drop(columns=['Region_names'])
        # df now is columns: target_sector target-country-iso3 deltaPollutant dQ

        # merge with POLLUTANTS
        df['target-sector'] = df['target-sector'].astype(str)
        # ! CO2 for now
        all_pollutants = self.ALL_POLLUTANTS.query("POLLUTANT_FRACTION == 'CO2'").copy()
        all_pollutants['target-sector'] = all_pollutants['target-sector'].astype(str)
        all_pollutants = all_pollutants.groupby(['target-country-iso3','target-sector']).agg({'POLLUTANT_VALUE':'sum'}).reset_index()

        df = df.merge(all_pollutants, how='left', on=['target-country-iso3','target-sector'])
        df['deltaPollutant_nostructuralchange'] = (df['dQ'] / df['q_base']) * df['POLLUTANT_VALUE']
        df['deltaPollutant_nostructuralchange'] = df['deltaPollutant_nostructuralchange'].fillna(0)
        df['deltaPollutant'] = df['dEmissions']
        df['qPollutant'] = df['POLLUTANT_VALUE']

        # merge with PROCESS EMISSIONS
        all_process_emissions = self.ALL_PROCESS_EMISSIONS
        all_process_emissions['target-sector'] = all_process_emissions['target-sector'].astype(str)
        df = df.merge(all_process_emissions, 
                      how='left', on=['target-country-iso3','target-sector'])
        # originally in tonnes (Y_2019) to have the same unit as POLLUTANTS multiply
        df['deltaProcess'] = (df['dQ'] / df['q_base']) * df['Y_2019'] * 1000
        df['deltaProcess'] = df['deltaProcess'].fillna(0)
        df['Y_2019'] = df['Y_2019'] * 1000
        df = df.rename(columns={'Y_2019':'qProcess'})

        df = df.groupby(['target-country-iso3','target-sector']).agg({'deltaPollutant':'sum', 'qPollutant':'sum',
                                                                                           'deltaProcess':'sum', 'qProcess':'sum', 
                                                                                           'deltaPollutant_nostructuralchange':'sum'})\
        .reset_index()

        ret_ = pd.concat([df])

        return ret_