# -*- coding: utf-8 -*-
"""
Created on Mon May  8 16:21:19 2023

@author: meimei
"""
import pandas as pd
import numpy as np
import openpyxl
import os
from SourceCode.utils import temporary_storage
from SourceCode.utils import resolve_hyphen, resolve_comma, resolve_all
from scipy.sparse import csr_matrix
# from alive_progress import alive_bar
from concurrent import futures
# from tqdm import tqdm
from SourceCode.utils import logging
from SourceCode.utils import MRIO_df_to_vec, MRIO_vec_to_df
from SourceCode.exog_vars import exog_vars

class scenario:
    """
    A policy scenario including the following elements:
    * Carbon tax
    * CBAM
    * Final demand
    * Investment by
    * Investment converter (adjustment)
    * Supply constraints (adjustment)
    * Price change
    * Input-output coefficients (adjustment)

    Attributes
    ------
    EXOG_VARS : exog_vars
        exog_vars object containing exogenous variables

    scenario_path : str
        path to the scenario file

    Log : logging
        logging object used for writing logs

    Methods
    -------

    set_carbon_tax
        Reads out carbon tax specification from the scenario file and constructs the necessary
        long-form matrix of tax incidences. Note: the function uses a parallelized approach
        and local storage (temporary storage) when construction the matrices due to the size
        of the necessary matrices.

    carbon_tax_rate_loop(country:str)
        works together with `set_carbon_tax`, it is the internal parallel loop function for
        calculating carbon tax matrices in a parallel manner for each of the countries specified
        in the policy scenario

    set_tax_rate(carbon_tax_incidence:pd.DataFrame)
        sets the actual tax rate based on the carbon tax incidence calculated from carbon taxes



    """
    def __init__(self, EXOG_VARS:exog_vars, scenario_path:str, Log:logging, year:int, years):
        self.scenario_file = scenario_path
        self.scenario_data = openpyxl.load_workbook(scenario_path, read_only=True)
        # self.name = scenario_name

        self.REGIONS = EXOG_VARS.R
        self.PRODUCTS = EXOG_VARS.P
        self.IND_BASE = EXOG_VARS.IND_BASE.reset_index()

        self.HH_BASE = EXOG_VARS.HH_BASE # type: ignore
        self.GOV_BASE = EXOG_VARS.GOV_BASE # type: ignore
        self.FCF_BASE = EXOG_VARS.FCF_BASE # type: ignore

        self.regions_length = self.REGIONS.shape[0]
        self.products_length = self.PRODUCTS.shape[0]

        self.temp = temporary_storage("Temp")
        self.tax_rate = pd.DataFrame()
        self.ee_exog = pd.DataFrame()

        self.Log = Log

        self.YEAR = year
        self.YEARS = years

        # initialize scenario values

        self.set_fd_exog()
        self.set_hh_permanent()

    def set_carbon_tax(self):
        # first we read in the scenario file, the columns are set in the template
        try:
            tax_rate = pd.read_excel(self.scenario_file, sheet_name="Carbon tax", skiprows=14)
            tax_rate = tax_rate[['Country ISO*','Emitting sectors covered*','Fuel sectors covered*',self.YEAR]]
            tax_rate.columns = ['REG_imp','PROD_COMM','TRAD_COMM','delta_tax']

        except (ValueError, KeyError):
            # catch if there is no sheet
            tax_rate = pd.DataFrame(columns=['REG_imp','PROD_COMM','TRAD_COMM','delta_tax'])

        # setting up for parallel processing
        self.tax_rate = tax_rate

        # for debugging
        # self.carbon_tax_rate_loop('USA')
        
        # print("Generating carbon tax files... Parallel started.")
        # tax rate files are generated by REG_imp country
        # with futures.ThreadPoolExecutor() as executor:
            # results = executor.map(self.carbon_tax_rate_loop, tax_rate['REG_imp'].unique())
            # results = list(tqdm(executor.map(self.carbon_tax_rate_loop, tax_rate['REG_imp'].unique()), 
                    #   total=len(tax_rate['REG_imp'].unique())))
            
        # del results
        tax_rate = self.carbon_tax_rate_loop()
        self.tax_rate = tax_rate
        self.carbon_tax_countries = list(tax_rate['REG_imp'].unique())

        return True


    def carbon_tax_rate_loop(self, country:str=None):
        """Parallel loop function for generating tax matrices by country. Saves the tax rate
        matrices in file.

        Parameters
        ----------
        country : str
            country to generate carbon tax file for

        Returns
        -------
        bool
            Returns True if completed
        """
          
        # first retrieve the tax rate file from the class
        tax_rate = self.tax_rate

        # TODO REG_exp is ALL for now
        tax_rate['REG_exp'] = 'ALL'
        # tax_rate_country = tax_rate[tax_rate['REG_imp']==country].copy()

        # process flows_table, for simplicity the flows table (excel) allows flows to
        # be allocated to multiple sectors either in hyphen e.g. 10-30 or comma e.g.
        # 10,11,15 format, these are parsed to actual sectors here

        tax_rate = resolve_hyphen(tax_rate, 'PROD_COMM')
        tax_rate = resolve_comma(tax_rate, 'PROD_COMM')
        tax_rate = resolve_hyphen(tax_rate, 'TRAD_COMM')
        tax_rate = resolve_comma(tax_rate, 'TRAD_COMM')

        tax_rate = resolve_comma(tax_rate, 'REG_imp')

        # treatment of ALL in PROD_COMM, ie all upstream sectors impacted
        tax_rate = resolve_all(tax_rate, 'PROD_COMM', [x for x in np.arange(1,121)] + ['FD_1','FD_2','FD_3','FD_4','FD_5','FD_6'])
        tax_rate = resolve_all(tax_rate, 'TRAD_COMM', [x for x in np.arange(1,121)])
        tax_rate = resolve_all(tax_rate, 'REG_exp', self.REGIONS['Region_acronyms'].to_list())
        tax_rate = resolve_all(tax_rate, 'REG_imp', self.REGIONS['Region_acronyms'].to_list())
        
        tax_rate = tax_rate.groupby(['REG_exp','REG_imp','PROD_COMM','TRAD_COMM']).aggregate({'delta_tax':'sum'}).reset_index()

        tax_rate = tax_rate.rename(columns={'delta_tax':'ctax'})
        self.temp.save_to_pickle(tax_rate, "carbon_tax_rate".format(country))

        return tax_rate
    
    def set_tax_rate(self, carbon_tax_incidence):
        # TODO: deprecated
        try:
            tax_rate = pd.read_excel(self.scenario_file, sheet_name="tax_scenarios")
        except (ValueError, KeyError):
            # catch if there is no sheet
            tax_rate = pd.DataFrame(columns=['REG_imp','PROD_COMM','REG_exp','TRAD_COMM','delta_tax','type'])

        # TODO: deprecated
        tax_rate = tax_rate[tax_rate['type']=='simple'].drop(columns=['type'])

        tax_rate = pd.concat([tax_rate, carbon_tax_incidence])

        # ! RN it only gets values from carbon tax incidence
        # ! therefore there is no parsing necessary bc that is already
        # ! parsed data

        # aggregate if there are multiple taxes, this generally should
        # NOT be the case, report duplicates first
        tax_rate = tax_rate.groupby(['REG_imp','PROD_COMM','TRAD_COMM','REG_exp']).agg({'delta_tax':'sum'}).reset_index()

        tax_rate_hh = tax_rate[tax_rate["PROD_COMM"].str.contains("FD_")]
        # ! THIS IS SO WRONG (no-weighting)
        tax_rate_hh = tax_rate_hh.groupby(['REG_imp','PROD_COMM','TRAD_COMM','REG_exp']).agg({'delta_tax':'sum'}).reset_index()
        tax_rate_hh = tax_rate_hh.rename(columns={"delta_tax":"delta_tax_hh"})
        
        self.tax_rate_hh = tax_rate_hh

        tax_rate = tax_rate[~tax_rate["PROD_COMM"].str.contains('FD_')]
        tax_rate = tax_rate.set_index(["REG_imp","PROD_COMM","TRAD_COMM","REG_exp"])

        self.tax_rate = tax_rate

        return True
    
    # ^ ------------------------------------
    # ^       CBAM SHOULD COME HERE         
    # ^ ------------------------------------

    # ^ ------------------------------------
    # ^   Sheet: Final demand               
    # ^ ------------------------------------

    def assign_price_change(self, tax_rate, tax_rate_hh, price_change):
        ind_base = self.IND_BASE
        ind_base = ind_base.astype({'PROD_COMM':'str', 'TRAD_COMM':'str'})
        # tax rate
        # REG_imp PROD_COMM TRAD_COMM REG_exp <- all in index, delta_tax is value
        tax_rate_ = tax_rate.copy()
        tax_rate_hh_ = tax_rate_hh.copy()
        # price change
        # 'REG_exp','REG_imp','TRAD_COMM','PROD_COMM','Value','Type'

        # ! bring in FD numbers (for HH for now)
        HH = self.HH_BASE.reset_index()
        # REG_imp REG_exp TRAD_COMM
        HH['PROD_COMM'] = 'FD_1'
        HH = HH.rename(columns={'VIPA':'z_bp'})
        # REG_imp REG_exp TRAD_COMM PROD_COMM z_bp

        # ! PRICE CHANGE (tax) is Absolute now

        tax_change = price_change[price_change['Type'].str.contains("tax")].copy()
        # ! for testing there is no need for ALL 
        # ! WE HAVE ONLY SINGLE COUNTRY CASE!!!

        tax_change = resolve_comma(tax_change, "TRAD_COMM")
        tax_change = resolve_comma(tax_change, "PROD_COMM")

        # IF VALUE is absolute we need to proportionally scale!
        tax_change_rel = tax_change[~tax_change['Type'].str.contains("abs")].copy().drop(columns=['Type','line'])
        tax_change_abs = tax_change[tax_change['Type'].str.contains("abs")].copy().drop(columns=['Type'])
        
        # we want to proceed by line
        tax_change_abs = tax_change_abs.astype({'PROD_COMM':'str', 'TRAD_COMM':'str'})

        # merge to MRIO
        ind_full = pd.concat([ind_base[['REG_imp','REG_exp','PROD_COMM','TRAD_COMM','z_bp']], HH])
        ind_full = ind_full.astype({'TRAD_COMM':'str'})
        tax_change_abs = tax_change_abs.merge(ind_full, how='left', 
                             on=['REG_imp','REG_exp','PROD_COMM','TRAD_COMM']).fillna(0)
        

        tax_change_abs['line_share'] = tax_change_abs['z_bp'] / tax_change_abs.groupby(['line'])['z_bp'].transform('sum')
        tax_change_abs['line_share'] = tax_change_abs['line_share'].fillna(0)
        tax_change_abs['Value'] = tax_change_abs['line_share'] * tax_change_abs['Value']
        tax_change_abs['Value'] = tax_change_abs['Value'].fillna(0)
        # proceed to calculate relative change
        tax_change_abs['rel_value'] = (tax_change_abs['Value'] / tax_change_abs['z_bp']) * 100
        tax_change_abs = tax_change_abs.groupby(['REG_imp','REG_exp','PROD_COMM','TRAD_COMM']).agg({'rel_value':'sum'})
        tax_change_abs = tax_change_abs.reset_index()
        tax_change_abs = tax_change_abs.rename(columns={'rel_value':'Value'})

        tax_change = pd.concat([tax_change_abs, tax_change_rel])

        # IO from here
        tax_change_ = tax_change[~tax_change['PROD_COMM'].str.contains("FD_")]
        tax_rate_ = tax_rate_.merge(tax_change_, how='outer', on=['REG_imp','PROD_COMM','REG_exp','TRAD_COMM'])
        tax_rate_ = tax_rate_.fillna(0)
        tax_rate_['delta_tax'] = tax_rate_['delta_tax'] + tax_rate_['Value']
        tax_rate_ = tax_rate_.drop(columns=['Value'])

        # HH here
        tax_change_ = tax_change[tax_change['PROD_COMM'].str.contains("FD_")]
        tax_rate_hh_ = tax_rate_hh_.merge(tax_change_, how='outer', on=['REG_imp','PROD_COMM','REG_exp','TRAD_COMM'])
        tax_rate_hh_ = tax_rate_hh_.fillna(0)
        tax_rate_hh_['delta_tax_hh'] = tax_rate_hh_['delta_tax_hh'] + tax_rate_hh_['Value']
        tax_rate_hh_ = tax_rate_hh_.drop(columns=['Value'])

        return tax_rate_, tax_rate_hh_

    def set_fd_exog(self):
        # columns to be passed on
        columns_ = ['REG_exp','REG_imp','TRAD_COMM','PROD_COMM',self.YEAR,'Type']

        try:
            fd_exog = pd.read_excel(self.scenario_file, sheet_name='Final demand', skiprows=14)
            fd_exog = fd_exog[['Producing country ISO*','Consuming country ISO*','Product code*',
                                 'FD code*',self.YEAR,'Type*']]
            fd_exog.columns = columns_
        except (ValueError, KeyError):
            fd_exog = pd.DataFrame(columns=columns_)

        fd_exog = fd_exog.rename(columns={self.YEAR:'Value'})

        # add index before resolving
        fd_exog['Line'] = np.arange(len(fd_exog)).tolist()

        fd_exog = resolve_comma(fd_exog, "REG_imp")
        fd_exog = resolve_all(fd_exog, "REG_imp", self.REGIONS['Region_acronyms'].to_list())

        fd_exog = resolve_comma(fd_exog, "REG_exp")
        fd_exog = resolve_all(fd_exog, "REG_exp", self.REGIONS['Region_acronyms'].to_list())

        fd_exog = resolve_comma(fd_exog, "TRAD_COMM")
        fd_exog = resolve_hyphen(fd_exog, "TRAD_COMM")
        fd_exog = resolve_all(fd_exog, "TRAD_COMM", [str(x) for x in np.arange(1,121)])

        fd_exog = resolve_comma(fd_exog, "PROD_COMM")
        fd_exog = resolve_all(fd_exog, "PROD_COMM", ['FD_1','FD_3','FD_4'])

        # ? Scenario.fd_exog structure is the following:
        # ? REG_imp | TRAD_COMM | PROD_COMM | Value | Type
        # ? such as PROD_COMM can only by FD_1, FD_2 ... FD_06
        # ? Type can be: abs-b [absolute-proportional-base] | abs [absolute-proportional-new] 
        # ? | rel [relative] | rel-b [relative to baseline]
        # ? if absolute is used with multiple sectors / countries
        # ? then numbers are proportionally spread out
        # ? proportionality is either to the base [abs-b] or to the current FD vector [abs]
        # TODO: abs is to be implemented later [with annualized model version]
        # TODO: rel is to be implemented later [with annualized model version]

        # WE CALCULATE FD_EXOG types here, bc the scenario class
        # should have direct impacts

        # ! INV is missing [FD_5 - FD_6]
        # ! NPISH is missing [FD_2]

        fd_01_initial = self.HH_BASE.reset_index().rename(columns={'VIPA':'FD_1'})
        fd_03_initial = self.GOV_BASE.reset_index().rename(columns={'VIGA':'FD_3'})
        fd_04_initial = self.FCF_BASE.reset_index().rename(columns={'VDFA':'FD_4'})
        # | REG_exp | REG_imp | TRAD_COMM |

        fd_initial = fd_01_initial.merge(fd_03_initial, how="outer", on=['REG_exp','REG_imp','TRAD_COMM']).merge(fd_04_initial, how="outer", on=['REG_exp','REG_imp','TRAD_COMM'])
        fd_initial = pd.melt(fd_initial, id_vars=['REG_exp','REG_imp','TRAD_COMM'],
                              var_name='PROD_COMM', value_name='y0')
        fd_initial['y0'] = fd_initial['y0'].fillna(0)
        del fd_01_initial, fd_03_initial, fd_04_initial
        # | REG_imp | REG_exp | TRAD_COMM | PROD_COMM [FD_1-FD_4] | y0 #

        fd_initial = fd_initial.astype({'TRAD_COMM':'str'})
        fd_exog = fd_exog.merge(fd_initial, how='left', on=['REG_imp','REG_exp','TRAD_COMM','PROD_COMM'])
        fd_exog['dy'] = 0.0

        # assigned vars dict
        # variables = {}

        # # ? assign
        # df_assign = fd_exog[fd_exog['Type'].str.contains('assign')].copy()

        # for i, r in df_assign.iterrows():
        #     name = r['Value'].replace("[TRAD_COMM]",str(r['TRAD_COMM'])).replace("[REG_imp]",str(r['REG_imp'])).replace("[REG_exp]",str(r['REG_exp'])).replace("[PROD_COMM]",str(r['PROD_COMM']))
        #     match_ = (df_assign['REG_imp']==r['REG_imp']) & (df_assign['TRAD_COMM']==r['TRAD_COMM']) & (df_assign['PROD_COMM']==r['PROD_COMM']) & (df_assign['REG_exp']==r['REG_exp'])
        #     variables[name] = variables[name] + df_assign.loc[match_, 'y0'] #type: ignore

        # variables_df = pd.DataFrame({"index": variables.keys(), "value": [x.values[0] if len(x)!=0 else 0 for x in variables.values()]})

        # # ? eval
        # # ? eval can access both variables_df and fd_exog
        # df_eval = fd_exog[fd_exog['Type'].str.contains('eval')].copy()

        # for i, r in df_eval.iterrows():
        #     match_ = (df_eval['REG_imp']==r['REG_imp']) & (df_eval['TRAD_COMM']==r['TRAD_COMM']) & (df_assign['PROD_COMM']==r['PROD_COMM']) & (df_assign['REG_exp']==r['REG_exp'])
        #     exp = r['Value'].replace("[PROD_COMM]",str(r['PROD_COMM'])).replace("[TRAD_COMM]",str(r['TRAD_COMM'])).replace("[REG_imp]",str(r['REG_imp'])).replace("[REG_exp]",str(r['REG_exp']))
        #     df_eval.loc[match_, 'dy'] = eval(exp)

        # ? abs-b: abs-b is absolute impact based on Y0
        # ? if multiple specified from something, then spread out proportionally

        df_absb = fd_exog[fd_exog['Type'].str.contains('abs-b')].copy()
        # calculate share by line
        df_absb['share'] = df_absb['y0'] / df_absb.groupby(['Line'])['y0'].transform('sum')
        df_absb['dy'] = df_absb['Value'] * df_absb['share']

        # ? rel-b

        df_relb = fd_exog[fd_exog['Type'].str.contains('rel-b')].copy()
        df_relb['dy'] = df_relb['y0'] * df_relb['Value']

        # ! LINES either overwrite each other (last one stays) or appended (sum)
        # ! only SUM for now!

        # df_impacts = pd.concat([df_eval, df_absb, df_relb])
        df_impacts = pd.concat([df_absb, df_relb])
        # ? REG_imp | REG_exp | TRAD_COMM | PROD_COMM [FD_1] | dy
        df_impacts = df_impacts.drop(columns=['Value','y0','Line'])
        df_impacts = df_impacts.groupby(['REG_exp','REG_imp','TRAD_COMM','PROD_COMM']).agg({'dy':'sum'}).reset_index()

        self.fd_exog = df_impacts

        return True

    # ^ //////////////////////////////////////

    def set_hh_permanent(self):
        # columns to be passed on
        columns_ = ['REG_exp','REG_imp','TRAD_COMM',self.YEAR,'Type']

        try:
            hh_exog = pd.read_excel(self.scenario_file, sheet_name='HH permanent', skiprows=14)
            hh_exog = hh_exog[['Producing country ISO*','Consuming country ISO*','Product code*',
                                 self.YEAR,'Type*']]
            hh_exog.columns = columns_
        except (ValueError, KeyError):
            hh_exog = pd.DataFrame(columns=columns_)

        hh_exog = hh_exog.rename(columns={self.YEAR:'Value'})

        # add index before resolving
        hh_exog['Line'] = np.arange(len(hh_exog)).tolist()

        hh_exog = resolve_comma(hh_exog, "REG_imp")
        hh_exog = resolve_all(hh_exog, "REG_imp", self.REGIONS['Region_acronyms'].to_list())

        hh_exog = resolve_comma(hh_exog, "REG_exp")
        hh_exog = resolve_all(hh_exog, "REG_exp", self.REGIONS['Region_acronyms'].to_list())

        hh_exog = resolve_comma(hh_exog, "TRAD_COMM")
        hh_exog = resolve_hyphen(hh_exog, "TRAD_COMM")
        hh_exog = resolve_all(hh_exog, "TRAD_COMM", [str(x) for x in np.arange(1,121)])

        fd_initial = self.HH_BASE.reset_index().rename(columns={'VIPA':'VIPA0'})
        # | REG_exp | REG_imp | TRAD_COMM |

        fd_initial = fd_initial.astype({'TRAD_COMM':'str'})
        hh_exog = hh_exog.merge(fd_initial, how='left', on=['REG_imp','REG_exp','TRAD_COMM'])
        hh_exog['dy'] = 0.0

        # ? rel-b

        df_relb = hh_exog[hh_exog['Type'].str.contains('rel-b')].copy()
        df_relb['dy'] = df_relb['VIPA0'] * df_relb['Value']

        # df_impacts = pd.concat([df_eval, df_absb, df_relb])
        df_impacts = pd.concat([df_relb])
        # ? REG_imp | REG_exp | TRAD_COMM | PROD_COMM [FD_1] | dy
        df_impacts = df_impacts.drop(columns=['Value','Line'])
        df_impacts = df_impacts.groupby(['REG_exp','REG_imp','TRAD_COMM']).agg({'dy':'sum'}).reset_index()

        self.hh_exog = df_impacts

        return True

    # ^ //////////////////////////////////////
    
    # ^ ------------------------------------
    # ^   Sheet: Investment BY sector       
    # ^ ------------------------------------

    def set_exog_inv(self, investment_base):
        # columns to be passed on
        columns_ = ['REG_imp','PROD_COMM',self.YEAR,'Type']

        try:
            inv_exog = pd.read_excel(self.scenario_file, sheet_name='Investment by', skiprows=14)
            inv_exog = inv_exog[['Country ISO*','Sector investing code*',self.YEAR,'Type*']]
            inv_exog.columns = columns_
        except (ValueError, KeyError):
            inv_exog = pd.DataFrame(columns=columns_)

        inv_exog = inv_exog.rename(columns={self.YEAR:'Value'})

        # add index before resolving
        inv_exog['Line'] = np.arange(len(inv_exog)).tolist()

        inv_exog = resolve_comma(inv_exog, "REG_imp")
        inv_exog = resolve_all(inv_exog, "REG_imp", self.REGIONS['Region_acronyms'].to_list())

        inv_exog = resolve_comma(inv_exog, "PROD_COMM")
        inv_exog = resolve_hyphen(inv_exog, "PROD_COMM")
        inv_exog = resolve_all(inv_exog, "PROD_COMM", [x for x in np.arange(1,121)])

        # ? Scenario.fd_exog structure is the following:
        # ? REG_imp | PROD_COMM | Value | Type
        # ? Type can be: abs-b [absolute-proportional-base] | abs [absolute-proportional-new] 
        # ? | rel [relative] | rel-b [relative to baseline]
        # ? if absolute is used with multiple sectors / countries
        # ? then numbers are proportionally spread out
        # ? proportionality is either to the base [abs-b] or to the current FD vector [abs]
        # TODO: abs is to be implemented later [with annualized model version]
        # TODO: rel is to be implemented later [with annualized model version]
        # TODO: rel-b is to be implemented later !! - we don't have investment baseline BY 
        # TODO: investing sector

        # ? abs-b: abs-b is absolute impact based on Y0
        # ? if multiple specified from something, then spread out proportionally

        df_absb = inv_exog[inv_exog['Type'].str.contains('abs-b')].copy()
        df_absb = df_absb.merge(investment_base, how='left', on=['REG_imp','PROD_COMM'])
        # calculate share by line
        df_absb['dk'] = df_absb['Value']
        df_absb['share'] = df_absb['dk_base'] / df_absb.groupby(['Line'])['dk_base'].transform('sum')
        df_absb['dk'] = df_absb['Value'] * df_absb['share']
        df_absb = df_absb[['REG_imp','PROD_COMM','dk']].copy()

        # ? rel-b: rel-b is relative to last year
        df_relb = inv_exog[inv_exog['Type'].str.contains('rel-b')].copy()
        df_relb = df_relb.merge(investment_base, how='left', on=['REG_imp','PROD_COMM'])
        df_relb['dk'] = df_relb['dk_base'] * df_relb['Value']
        df_relb = df_relb[['REG_imp','PROD_COMM','dk']].copy()

        # ! LINES either overwrite each other (last one stays) or appended (sum)
        # ! only SUM for now!

        df_impacts = pd.concat([df_absb])
        df_impacts = pd.concat([df_absb,df_relb])
        # ? REG_imp | PROD_COMM | dk
        df_impacts = df_impacts.groupby(['REG_imp','PROD_COMM']).agg({'dk':'sum'}).reset_index()

        self.inv_exog = df_impacts.astype({'PROD_COMM':'int'})

        return True
    
    # ^ //////////////////////////////////////

        # ^ ------------------------------------
    # ^   Sheet: Exogenous household transfer       
    # ^ ------------------------------------

    def set_exog_inc(self):
        # columns to be passed on
        columns_ = ['REG_imp',self.YEAR,'Type']

        try:
            inc_exog = pd.read_excel(self.scenario_file, sheet_name='Exog hh transfer', skiprows=14)
            inc_exog = inc_exog[['Country ISO*',self.YEAR,'Type*']]
            inc_exog.columns = columns_
        except (ValueError, KeyError):
            inc_exog = pd.DataFrame(columns=columns_)

        inc_exog = inc_exog.rename(columns={self.YEAR:'Value'})

        inc_exog = resolve_comma(inc_exog, "REG_imp")
        inc_exog = resolve_all(inc_exog, "REG_imp", self.REGIONS['Region_acronyms'].to_list())

        # ? Scenario.inc_exog structure is the following:
        # ? REG_imp | Value | Type

        df_absb = inc_exog[inc_exog['Type'].str.contains('abs-b')].copy()
        df_absb['dlabor_exog'] = df_absb['Value']
        df_absb = df_absb[['REG_imp','dlabor_exog']].copy()

        df_impacts = pd.concat([df_absb])
        # ? REG_imp | dlabor_exog
        df_impacts = df_impacts.groupby(['REG_imp']).agg({'dlabor_exog':'sum'}).reset_index()

        self.inc_exog = df_impacts

        return df_impacts
    
    # ^ //////////////////////////////////////

    # ^ ------------------------------------
    # ^   Sheet: Exogenous energy intensity change       
    # ^ ------------------------------------

    def set_exog_ener_intensity(self):
        # columns to be passed on
        columns_ = ['REG_imp','PROD_COMM',self.YEAR]

        try:
            ee_exog = pd.read_excel(self.scenario_file, sheet_name='Energy intensity', skiprows=14)
            ee_exog = ee_exog[['Country ISO*','Sector*',self.YEAR]]
            ee_exog.columns = columns_
        except (ValueError, KeyError):
            ee_exog = pd.DataFrame(columns=columns_)

        ee_exog = ee_exog.rename(columns={self.YEAR:'Value'})

        ee_exog = resolve_comma(ee_exog, "REG_imp")
        ee_exog = resolve_all(ee_exog, "REG_imp", self.REGIONS['Region_acronyms'].to_list())

        ee_exog = resolve_comma(ee_exog, "PROD_COMM")
        ee_exog = resolve_hyphen(ee_exog, "PROD_COMM")
        ee_exog = resolve_all(ee_exog, "PROD_COMM", [x for x in np.arange(1,121)])

        ee_exog = ee_exog.groupby(['REG_imp','PROD_COMM']).agg({'Value':'sum'}).reset_index()
        ee_exog = ee_exog.rename(columns={'Value':'ee_change'})

        self.ee_exog = ee_exog

    # ^ //////////////////////////////////////

    # ^ -----------------------------------------------
    # ^   Sheet: Investment converter adjustment       
    # ^ -----------------------------------------------

    def set_inv_conv_adj(self, INV_CONV):
        # columns to be passed on
        columns_ = ['REG_imp','PROD_COMM','TRAD_COMM','Value','Type']

        try:
            inv_conv_adj = pd.read_excel(self.scenario_file, sheet_name='Investment converter', skiprows=14)
            inv_conv_adj = inv_conv_adj[['Country ISO*','Investing sector code*','Investment good sector code*',self.YEAR,'Type*']]
            inv_conv_adj.columns = columns_
        except (ValueError, KeyError):
            inv_conv_adj = pd.DataFrame(columns=columns_)

        df_inv_conv = INV_CONV.copy()

        if len(inv_conv_adj) > 0:

            inv_conv_adj = resolve_comma(inv_conv_adj, "REG_imp")
            inv_conv_adj = resolve_all(inv_conv_adj, "REG_imp", self.REGIONS['Region_acronyms'].to_list())

            inv_conv_adj = resolve_comma(inv_conv_adj, "PROD_COMM")
            inv_conv_adj = resolve_hyphen(inv_conv_adj, "PROD_COMM")
            inv_conv_adj = resolve_all(inv_conv_adj, "PROD_COMM", [x for x in np.arange(1,121)])

            inv_conv_adj = resolve_comma(inv_conv_adj, "TRAD_COMM")
            inv_conv_adj = resolve_hyphen(inv_conv_adj, "TRAD_COMM")
            inv_conv_adj = resolve_all(inv_conv_adj, "TRAD_COMM", [x for x in np.arange(1,121)])

            # ? Type can be:
            # ? abs-b | rel-b | abs | rel | replace
            # TODO: abs is to be implemented later
            # TODO: abs is to be implemented later
            # TODO: abs-b is to be implemented later [with annualized model version]
            # TODO: rel-b is to be implemented later [with annualized model version]

            # ! NOTE: with this setup there is no differentiation in terms of investment conversion
            # ! between INDUCED | RECYCLED | EXOG investment types
            # TODO: might need to change this

            # ? replace: replace is direct replacement of INV_CONV coeffs

            df_replace = inv_conv_adj[inv_conv_adj['Type'].str.contains('replace')].copy()
            # calculate 
            df_inv_conv = df_inv_conv.astype({'TRAD_COMM':'str'})
            df_inv_conv = df_inv_conv.merge(df_replace, how='outer', on=['REG_imp','PROD_COMM','TRAD_COMM'])
            df_inv_conv.loc[~df_inv_conv['Value'].isna(),'input_coeff'] = df_inv_conv['Value']

            # ! ALWAYS rebalancing to 1 [column-wise | PROD_COMM]
            df_inv_conv['new_input_coeff'] = df_inv_conv['input_coeff'] * (1 / df_inv_conv.groupby(['REG_imp','PROD_COMM'])['input_coeff'].transform('sum'))
            df_inv_conv = df_inv_conv.fillna(0)
            df_inv_conv['input_coeff'] = df_inv_conv['new_input_coeff']

            df_inv_conv = df_inv_conv.drop(columns=['Type','Value','new_input_coeff'])

        return df_inv_conv

    # ^ //////////////////////////////////////

    # ^ -----------------------------------------------
    # ^   Sheet: Price change (tax or non-tax)         
    # ^ -----------------------------------------------

    def set_cost_shock(self):
        try:
            cost_shock = pd.read_excel(self.scenario_file, sheet_name="Price change", skiprows=14)
            cost_shock = cost_shock[['Producer country ISO*','Producer sector code*',self.YEAR,'Type*']]
            cost_shock.columns = ['REG_imp','PROD_COMM','Value','Type']
        except (ValueError, KeyError):
            cost_shock = pd.DataFrame(columns=['REG_imp','PROD_COMM','Value','Type'])

        # add LINE id
        cost_shock['line'] = range(len(cost_shock))

        cost_shock = resolve_comma(cost_shock, "REG_imp")
        cost_shock = resolve_all(cost_shock, "REG_imp", self.REGIONS['Region_acronyms'].to_list())

        cost_shock = resolve_comma(cost_shock, "PROD_COMM")
        cost_shock = resolve_hyphen(cost_shock, "PROD_COMM")
        cost_shock = resolve_all(cost_shock, "PROD_COMM", [x for x in np.arange(1,121)])

        # price changes are captured on the level of production sector, not 

        # ? rel -> used for non-tax type cost shocks, picked up by Prod_cost.prod_cost_impact
        # ? increases production cost of the good therefore reducing demand

        self.cost_shock = cost_shock

    # ^ //////////////////////////////////////

    # ^ -----------------------------------------------
    # ^   Sheet: Supply constraints                    
    # ^ -----------------------------------------------


    def set_supply_constraint(self):
        try:
            supply_constraint = pd.read_excel(self.scenario_file, sheet_name="Supply constraint", skiprows=14)
            supply_constraint = supply_constraint[['Country ISO*','Product code*',self.YEAR,'Type*']]
            supply_constraint.columns = ['REG_imp','PROD_COMM','Value','Type']
        except (ValueError, KeyError):
            supply_constraint = pd.DataFrame(columns=['REG_imp','PROD_COMM','Value','Type'])

        supply_constraint = resolve_comma(supply_constraint, 'REG_imp')
        supply_constraint = resolve_all(supply_constraint, 'REG_imp', self.REGIONS['Region_acronyms'].to_list())

        supply_constraint = resolve_comma(supply_constraint, 'PROD_COMM')
        supply_constraint = resolve_hyphen(supply_constraint, 'PROD_COMM')
        supply_constraint = resolve_all(supply_constraint, 'PROD_COMM', [x for x in np.arange(1,121)])

        self.supply_constraint = supply_constraint

    # ^ //////////////////////////////////////

    # ^ -----------------------------------------------
    # ^   Sheet: Supply constraints no labour impact                   
    # ^ -----------------------------------------------


    def set_supply_constraint_no_empl(self):
        try:
            supply_constraint_no_empl_change = pd.read_excel(self.scenario_file, sheet_name="Supply constraint no empl", skiprows=14)
            supply_constraint_no_empl_change = supply_constraint_no_empl_change[['Country ISO*','Product code*',self.YEAR,'Type*']]
            supply_constraint_no_empl_change.columns = ['REG_imp','PROD_COMM','Value','Type']
        except (ValueError, KeyError):
            supply_constraint_no_empl_change = pd.DataFrame(columns=['REG_imp','PROD_COMM','Value','Type'])

        supply_constraint_no_empl_change = resolve_comma(supply_constraint_no_empl_change, 'REG_imp')
        supply_constraint_no_empl_change = resolve_all(supply_constraint_no_empl_change, 'REG_imp', self.REGIONS['Region_acronyms'].to_list())

        supply_constraint_no_empl_change = resolve_comma(supply_constraint_no_empl_change, 'PROD_COMM')
        supply_constraint_no_empl_change = resolve_hyphen(supply_constraint_no_empl_change, 'PROD_COMM')
        supply_constraint_no_empl_change = resolve_all(supply_constraint_no_empl_change, 'PROD_COMM', [x for x in np.arange(1,121)])

        self.supply_constraint_no_empl_change = supply_constraint_no_empl_change

    # ^ //////////////////////////////////////

    # ^ -----------------------------------------------
    # ^   Sheet: Capital stock                    
    # ^ -----------------------------------------------


    def set_capital_stock_change(self):
        try:
            capital_change = pd.read_excel(self.scenario_file, sheet_name="Capital", skiprows=14)
            capital_change = capital_change[['Country ISO*','Investing sector code*',self.YEAR,'Type*']]
            capital_change.columns = ['REG_imp','PROD_COMM','Value','Type']
        except (ValueError, KeyError):
            capital_change = pd.DataFrame(columns=['REG_imp','PROD_COMM','Value','Type'])

        capital_change = resolve_comma(capital_change, 'REG_imp')
        capital_change = resolve_all(capital_change, 'REG_imp', self.REGIONS['Region_acronyms'].to_list())

        capital_change = resolve_comma(capital_change, 'PROD_COMM')
        capital_change = resolve_hyphen(capital_change, 'PROD_COMM')
        capital_change = resolve_all(capital_change, 'PROD_COMM', [x for x in np.arange(1,121)])

        self.capital_change = capital_change

    # ^ //////////////////////////////////////
    
    def set_io_changes(self):
        try:
            io_changes = pd.read_excel(self.scenario_file, sheet_name="Input-output coefficients", skiprows=14)
            io_changes = io_changes[['Origin country ISO*','Target country ISO*','Origin sector code*','Target sector code*',self.YEAR,'Type*']]
            io_changes.columns = ['REG_exp','REG_imp','TRAD_COMM','PROD_COMM','Value','Type']

            # index
            io_changes['line'] = range(len(io_changes))

            # resolve hyphens
            io_changes = resolve_hyphen(io_changes, 'TRAD_COMM')
            io_changes = resolve_hyphen(io_changes, 'PROD_COMM')

            io_changes = resolve_comma(io_changes, 'TRAD_COMM')
            io_changes = resolve_comma(io_changes, 'PROD_COMM')

            io_changes = resolve_all(io_changes, 'TRAD_COMM', [x for x in np.arange(1,121)])
            
            # Save inputs for Specific country
            io_changes_specific = io_changes[(io_changes['REG_exp']!='ALL') & (io_changes['REG_imp']!='ALL')].copy()
            # treatment of ALL in REG_exp
            pairs = io_changes[io_changes['REG_exp']=='ALL'][['REG_imp','PROD_COMM','TRAD_COMM','Value','Type','line']].copy()
            if len(pairs) > 0:
                pairs['key'] = 1
                keys = pd.DataFrame({
                    'REG_exp': self.REGIONS['Region_acronyms'].to_list(),
                    'key': 1
                })
                
                complement_ALL = keys.merge(pairs, how='left', on='key').drop(columns=['key'])
                io_changes = pd.concat([io_changes[io_changes['REG_exp']!='ALL'], complement_ALL])

                del complement_ALL
                
            # treatment of ALL in REG_imp
            pairs = io_changes[io_changes['REG_imp']=='ALL'][['REG_exp','PROD_COMM','TRAD_COMM','Value','Type','line']].copy()
            if len(pairs) > 0:
                pairs['key'] = 1
                keys = pd.DataFrame({
                    'REG_imp': self.REGIONS['Region_acronyms'].to_list(),
                    'key': 1
                })
                
                complement_ALL = keys.merge(pairs, how='left', on='key').drop(columns=['key'])
                io_changes = pd.concat([io_changes[io_changes['REG_imp']!='ALL'], complement_ALL])

                del complement_ALL
                
            # treatment of KEEP in REG_exp
            # total of input needs to be as specified, but keep distribution across REG_exp
            pairs = io_changes[io_changes['REG_exp']=='KEEP'][['REG_imp','PROD_COMM','TRAD_COMM','Value','Type','line']].copy()
            if len(pairs) > 0:
                # TODO: for now this is okay, but if we have more lines of scenario this might gonna cause issues
                pairs['key'] = 1
                keys = pd.DataFrame({
                    'REG_exp': self.REGIONS['Region_acronyms'].to_list(),
                    'key': 1
                })
                complement_ALL = keys.merge(pairs, how='left', on='key').drop(columns=['key'])
                # now we need to recalculate the relevant shares
                # complement_ALL is
                # REG_exp, REG_imp, PROD_COMM, TRAD_COMM, Value
                complement_ALL = complement_ALL.merge(self.IND_BASE[['REG_imp','REG_exp','PROD_COMM','TRAD_COMM','z_bp']], 
                                     how='left', on=['REG_imp','REG_exp','PROD_COMM','TRAD_COMM'])
                # calculate relevant share
                complement_ALL['REG_exp_share'] = \
                    complement_ALL['z_bp'] / complement_ALL.groupby(['REG_imp','PROD_COMM','TRAD_COMM'])['z_bp'].transform('sum')
                complement_ALL['Value'] = complement_ALL['Value'] * complement_ALL['REG_exp_share']
                complement_ALL = complement_ALL.drop(columns=['z_bp','REG_exp_share'])
                io_changes = pd.concat([io_changes[io_changes['REG_exp']!='KEEP'], complement_ALL])

                del complement_ALL

            # we might end up with duplicates, the latest assignment is the valid one
            io_changes = io_changes.sort_values(by='line').drop_duplicates(keep='last', subset=['REG_imp','REG_exp','PROD_COMM','TRAD_COMM']).drop(columns=['line'])
                
        except (ValueError, KeyError):
            io_changes = pd.DataFrame(columns=['REG_imp','PROD_COMM','REG_exp','TRAD_COMM','Type','Value'])
        
        self.io_changes = io_changes

        return io_changes

    def build_rev_split(self):
        # load tax revenue split
        rev_split = pd.read_excel(self.scenario_file, sheet_name="rev_split")
        self.rev_split = rev_split

        return self.rev_split

    def build_rev_proportion(self):
        # load proportional allocation
        rev_proportion = self.scenario_data["rev_proportional"]
        rev_proportion.reset_dimensions() # type: ignore
        rev_proportion = pd.DataFrame(rev_proportion.values) # type: ignore
        rev_proportion.columns = rev_proportion.iloc[0]
        rev_proportion = rev_proportion.drop(index=0)
        rev_proportion = rev_proportion.reset_index().drop(columns=["index"])
        # rev_proportion = pd.read_excel(scenariofile, "rev_proportional")

        for i in range(1,len(rev_proportion.columns)):
            colname = rev_proportion.columns[i]
            rev_proportion[colname] = pd.Series(rev_proportion[colname], dtype=float)

        self.rev_proportion = rev_proportion

        return self.rev_proportion
    
    def build_govt_spending(self):
        govt_spending = self.scenario_data["govt_spending"]
        govt_spending.reset_dimensions() # type: ignore
        govt_spending = pd.DataFrame(govt_spending.values) # type: ignore

        govt_spending.columns = govt_spending.iloc[0]
        govt_spending = govt_spending.drop(index=0)
        govt_spending = govt_spending.reset_index().drop(columns=["index"])
        govt_spending = govt_spending.rename(columns={"REG":"REG_imp", "PROD_COMM":"TRAD_COMM"})
        govt_spending["govt_spend"] = pd.Series(govt_spending["govt_spend"], dtype=float)
        
        self.govt_spending = govt_spending

        return self.govt_spending
    
    def build_inv_spending(self):
        inv_spending = self.scenario_data["inv_spending"]
        inv_spending.reset_dimensions() # type: ignore
        inv_spending = pd.DataFrame(inv_spending.values) # type: ignore

        inv_spending.columns = inv_spending.iloc[0]
        inv_spending = inv_spending.drop(index=0)
        inv_spending = inv_spending.reset_index().drop(columns=["index"])
        inv_spending = inv_spending.rename(columns={"REG":"REG_imp"})
        inv_spending["PROD_COMM"] = pd.Series(inv_spending["PROD_COMM"], dtype=int)
        inv_spending["inv_spend"] = pd.Series(inv_spending["inv_spend"], dtype=float)

        self.inv_spending = inv_spending

        return self.inv_spending
    
    def assign_bta(self, bta):
        self.bta = bta
    
    
